# To simplify references to GitHub:
github: "https://github.com/eic/"

# baseurl: /d1

collections:
  content:
    output: true
    permalink: /content/:title.html

  internal:
    output: true
    permalink: /internal/:title.html

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
